---
- name: Copy over current directory for repo build
  synchronize:
    src: ../../../../securedrop-signal-cli/
    dest: "{{ package_path }}"
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"
    recursive: yes
    rsync_opts: "{{ signal_cli_rsync_opts }}"

- name: Build securedrop-signal-cli Debian package.
  command: dpkg-deb --build {{ package_path }}

- name: Fetch newly built Debian packages back to localhost.
  fetch:
    src: "{{ package_path }}.deb"
    dest: "{{ signal_cli_build_deb_package_local_dest_dir }}"
    flat: yes
    fail_on_missing: yes
