---
# - name: Update apt cache.
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600
#   tags:
#     - apt
#     - build

- include: download_signal_cli.yml

- include: build-signal-cli-deb.yml
